name: Validate JSON

on:
  pull_request:
    paths:
      - '**.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: '**.json'

      - name: Validate JSON files
        id: validate
        run: |
          ERROR_LOG=""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [ -f "$file" ]; then
              echo "Validating $file"
              ERROR_OUTPUT=$(jq empty "$file" 2>&1 || true)
              if [ ! -z "$ERROR_OUTPUT" ]; then
                LINE_NUM=$(echo "$ERROR_OUTPUT" | grep -o "line [0-9]*" | cut -d' ' -f2)
                ERROR_LOG="$ERROR_LOG\n• $file (line $LINE_NUM): $ERROR_OUTPUT"
              fi
            fi
          done
          if [ ! -z "$ERROR_LOG" ]; then
            echo "error_log<<EOF" >> $GITHUB_ENV
            echo "$ERROR_LOG" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            exit 1
          fi

      - name: Comment on PR if validation fails
        if: failure()
        uses: actions/github-script@v7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **JSON Validation Failed**\n\n👋 Hello and thank you for helping with translations! We found some formatting issues:\n\n```\n${{ env.error_log }}\n```\n\n### Common fixes:\n1️⃣ Check for missing commas between items:\n```json\n{\n  "key1": "value1",  // ✅ Correct - has comma\n  "key2": "value2"   // ✅ Correct - no comma on last item\n}\n```\n\n2️⃣ Make sure quotes are properly closed:\n```json\n"key": "correct value",     // ✅ Correct\n"key": "missing quote,      // ❌ Wrong\n```\n\n3️⃣ Don\'t add comma after the last item:\n```json\n{\n  "first": "value",   // ✅ Comma here\n  "last": "value"     // ✅ No comma on last item\n}\n```\n\nNeed help? Feel free to ask and we\'ll assist you! Your contribution helps make ABRP accessible to more users worldwide. 🌍'
            })

      - name: Comment on PR if validation succeeds
        if: success()
        uses: actions/github-script@v7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✨ **Thank you for your translation contribution!**\n\nThe file format looks good and we\'ll review your changes soon.\n\nYour help in making ABRP accessible to more users is greatly appreciated! 🌟'
            })
