name: Validate Translations

on:
  pull_request:
    paths:
      - '**.json'
  push:
    paths:
      - '**.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check JSON syntax
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"
          strict: true

      - name: Report validation results
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ All JSON files are valid"
          else
            echo "❌ Found invalid JSON files"
            exit 1
          fi