name: Validate JSON

on:
  pull_request:
    paths:
      - '**.json'
  push:
    paths:
      - '**.json'

jobs:
  verify-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: |
            {
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            }
          INPUT_JSONS: $(find . -name "*.json" -type f | tr '\n' ',')