name: Validate Translations

on:
  pull_request:
    paths:
      - '**.json'
  push:
    paths:
      - '**.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Create Schema
        run: |
          echo '{
            "$schema": "http://json-schema.org/draft-07/schema#",
            "type": "object",
            "additionalProperties": {
              "type": "string"
            },
            "minProperties": 1
          }' > schema.json

      - name: Validate JSON files
        run: |
          for file in *.json; do
            if [ "$file" != "schema.json" ]; then
              echo "Validating $file..."
              ajv validate -s schema.json -d "$file" --strict=false || exit 1
            fi
          done